# 🔢 NumPy Basics

NumPy is Python’s core library for **numerical computing**. It provides the `ndarray` (N-dimensional array) type, which behaves similarly to a Python list but with several advantages:

- Optimized for high-performance numerical operations.
- Enables vectorized, elementwise computation without explicit loops.
- Handles large, homogeneous numeric data efficiently.

## 📦 Import NumPy

In [155]:
import numpy as np
from time import perf_counter

## ⚡ Speed Demonstration: Python List vs NumPy Array
Vectorized operations in NumPy execute faster than equivalent Python loops for large data sets.

In [156]:
N = 200_000

# Python list: add 5 to each element
py = list(range(N))
t0 = perf_counter()
py_plus5 = [x + 5 for x in py]
t1 = perf_counter()

# NumPy array: vectorized operation
arr = np.arange(N)
t2 = perf_counter()
arr_plus5 = arr + 5
t3 = perf_counter()

print(f"Python list time: {t1 - t0:.6f}s")
print(f"NumPy array time: {t3 - t2:.6f}s")

Python list time: 0.005121s
NumPy array time: 0.000272s


## 🛠️ Creating Arrays
Arrays can be constructed from Python lists or with built-in NumPy functions.

In [ ]:
# -------------------------------------------------------------
# 🔢 Creating NumPy Arrays
# -------------------------------------------------------------

# 1D and 2D arrays
a = np.array([1, 2, 3, 4])                 # 1D array from a Python list
b = np.array([[1, 2, 3], [4, 5, 6]])       # 2D array (matrix) from nested lists

print("1️⃣ One-dimensional array (a):")
print(a, "\n")

print("2️⃣ Two-dimensional array (b):")
print(b, "\n")

# -------------------------------------------------------------
# 🧱 Creating Special Arrays
# -------------------------------------------------------------
# NumPy has built-in functions for generating structured arrays easily.

print("3️⃣ Array of zeros (3x3):")
print(np.zeros((3, 3)), "\n")

print("4️⃣ Array of ones (2x4):")
print(np.ones((2, 4)), "\n")

print("5️⃣ Array filled with a constant value (2x2, filled with 7):")
print(np.full((2, 2), 7), "\n")

print("6️⃣ Identity matrix (3x3):")
print(np.eye(3))


1️⃣ One-dimensional array (a):
[1 2 3 4] 

2️⃣ Two-dimensional array (b):
[[1 2 3]
 [4 5 6]] 

3️⃣ Array of zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

4️⃣ Array of ones (2x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

5️⃣ Array filled with a constant value (2x2, filled with 7):
[[7 7]
 [7 7]] 

6️⃣ Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 📏 Ranges and Spacing
`arange` creates evenly spaced values by step size, while `linspace` generates a fixed number of values between a start and end point.

In [158]:
print("1️⃣ np.arange(10, 30, 5):")
print(np.arange(10, 30, 5))     # Values from 10 to 30 (exclusive), stepping by 5
print()

print("2️⃣ np.linspace(10, 30, 5):")
print(np.linspace(10, 30, 5))   # 5 evenly spaced values from 10 to 30 (inclusive)

1️⃣ np.arange(10, 30, 5):
[10 15 20 25]

2️⃣ np.linspace(10, 30, 5):
[10. 15. 20. 25. 30.]


## 🎲 Random Arrays (Modern API)
The `default_rng` generator is the recommended modern interface for random number generation.

In [159]:
rng = np.random.default_rng(42)

# 1️⃣ Random floating-point numbers
print("Random floats in [0, 1):")
print(rng.random((2, 3)))
print()

# 2️⃣ Random integers
print("Random integers between 0 and 99:")
print(rng.integers(0, 100, (3, 3)))

Random floats in [0, 1):
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]

Random integers between 0 and 99:
[[73 76 71]
 [78 51 12]
 [83 45 50]]


## 🔍 Inspecting Arrays
Common attributes of arrays include the number of dimensions (`ndim`), shape, total size, and data type.

In [160]:
A = np.arange(12).reshape(3, 4)
print("Array A:")
print(A, "\n")

print("1️⃣ Number of dimensions (ndim):", A.ndim)
print("2️⃣ Shape (rows, columns):", A.shape)
print("3️⃣ Total number of elements (size):", A.size)
print("4️⃣ Data type of elements (dtype):", A.dtype)

Array A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

1️⃣ Number of dimensions (ndim): 2
2️⃣ Shape (rows, columns): (3, 4)
3️⃣ Total number of elements (size): 12
4️⃣ Data type of elements (dtype): int64


## ➕ Elementwise Math and Broadcasting
NumPy automatically applies arithmetic operations elementwise. When array shapes differ but are compatible, broadcasting rules determine how data aligns.

In [161]:
X = np.array([1, 2, 3, 4])
Y = np.array([10, 20, 30, 40])

# 1️⃣ Element-wise addition
print("X + Y  →  Element-wise addition:")
print(X + Y, "\n")  # Each element in X adds to the corresponding element in Y

# 2️⃣ Element-wise multiplication
print("X * Y  →  Element-wise multiplication:")
print(X * Y, "\n")  # Each element in X multiplies with the corresponding element in Y

# 3️⃣ Broadcasting with a scalar
print("X + 5  →  Add a scalar (5) to every element in X:")
print(X + 5, "\n")  # NumPy automatically broadcasts the scalar to all elements

# 4️⃣ Using np.add() — same as X + Y
print("np.add(X, Y)  →  Function form of addition:")
print(np.add(X, Y))

X + Y  →  Element-wise addition:
[11 22 33 44] 

X * Y  →  Element-wise multiplication:
[ 10  40  90 160] 

X + 5  →  Add a scalar (5) to every element in X:
[6 7 8 9] 

np.add(X, Y)  →  Function form of addition:
[11 22 33 44]


## 🧮 Matrix Operations
The `@` operator performs matrix multiplication. The `np.dot` function behaves similarly for two-dimensional arrays.

In [162]:
M = np.arange(6).reshape(2, 3)   # 2×3 matrix → [[0,1,2],[3,4,5]]
N = np.arange(9).reshape(3, 3)   # 3×3 matrix → [[0,1,2],[3,4,5],[6,7,8]]

print("Matrix M:")
print(M, "\n")

print("Matrix N:")
print(N, "\n")

# 1️⃣ Matrix multiplication using @ operator (Python 3.5+)
print("M @ N  →  Matrix multiplication result:")
print(M @ N, "\n")

# 2️⃣ Equivalent operation using np.dot()
print("np.dot(M, N)  →  Same result as @:")
print(np.dot(M, N))

Matrix M:
[[0 1 2]
 [3 4 5]] 

Matrix N:
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

M @ N  →  Matrix multiplication result:
[[15 18 21]
 [42 54 66]] 

np.dot(M, N)  →  Same result as @:
[[15 18 21]
 [42 54 66]]


## ✂️ Indexing and Slicing
Array elements are accessed with `[row, column]` notation. Slicing syntax `start:stop` selects ranges (the stop index is excluded).

In [163]:
B = np.array([
    [5, 6, 7],
    [8, 9, 10],
    [1, 2, 3]
])

print("Array B:")
print(B, "\n")


# 1️⃣ Access a single element (B[row_index, column_index])
print("Element at row 0, column 2 → B[0, 2]:", B[0, 2])

# 2️⃣ Slice rows and columns
# B[1:, :2] means:
#   - rows 1 to end  → B[1:]
#   - first 2 columns → :2
print("\nSubarray (rows 1 to end, first 2 columns):")
print(B[1:, :2])


Array B:
[[ 5  6  7]
 [ 8  9 10]
 [ 1  2  3]] 

Element at row 0, column 2 → B[0, 2]: 7

Subarray (rows 1 to end, first 2 columns):
[[8 9]
 [1 2]]


## 🔄 Reshape and Transpose
Reshaping changes an array’s dimensions without altering data order. Transposition swaps rows and columns in two-dimensional arrays.

In [164]:
# Create a 2x3 array using arange and reshape:
# np.arange(6) → [0 1 2 3 4 5]
# reshape(2, 3) → 2 rows, 3 columns
C = np.arange(6).reshape(2, 3)
print("Original Array (C):")
print(C)
print("Shape:", C.shape, "\n")

# 1️⃣ Transpose the array
# C.T swaps rows and columns.
print("Transposed Array (C.T):")
print(C.T)
print("Shape:", C.T.shape, "\n")

# 2️⃣ Reshape the array
# Reshape changes dimensions while keeping the same total number of elements.
print("Reshaped Array (3 rows × 2 columns):")
print(C.reshape(3, 2))
print("Shape:", C.reshape(3, 2).shape)

Original Array (C):
[[0 1 2]
 [3 4 5]]
Shape: (2, 3) 

Transposed Array (C.T):
[[0 3]
 [1 4]
 [2 5]]
Shape: (3, 2) 

Reshaped Array (3 rows × 2 columns):
[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)


## 🔧 Type Conversion
Arrays store a single data type. Conversion can be performed using `astype`.

In [165]:
# Create an integer array with dtype explicitly set to int32
E = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", E)
print("Data type of E:", E.dtype, "\n")

# 1️⃣ Convert the array to a different data type (float64)
E_float = E.astype(np.float64)

print("Converted array:", E_float)
print("Data type after conversion:", E_float.dtype)

Original array: [1 2 3]
Data type of E: int32 

Converted array: [1. 2. 3.]
Data type after conversion: float64
